### ISSUE TITLE
JS minify failed on public/javascripts/app.js: TypeError: Cannot assign to read only property 'except' of [object Object]

### ISSUE THREAD

**Issue by rtruong** [brunch/terser-brunch#7]
When using uglify-js-brunch with the following configuration (from config.coffee):

```
exports.config =
  plugins:
    uglify:
      mangle:
        except: [ "require" ]
```

With the following command line:

```
brunch build --optimize
```

I get the following error.

```
error: JS minify failed on public/javascripts/app.js: TypeError: Cannot assign to read only property 'except' of [object Object]
```

I'm using node v0.10.5, brunch 1.6.3, and uglify-js-brunch 1.5.1.
